module.exports = {
	units: [
		{
			unitNo: '1',
			unitName: '1. 산과 염기',
			unitNoIcon: '../../common/img/2/science/num1.png',
			menuTarget: 'lesson-wrap1',
			chapters: [
				{
					chapterName: '',
					lessons: [
						{
							lessonNo: '1',
							lessonName: ' 산과 염기',
							play: '../special/special.html',
							ebook: '../index.html?skin=e-usb&page=3',
							lessonClass: '',
							attachments: {
								'수업 PPT': { path: '../common/attachments/sample.ppt' },
								활동지: { path: '../common/attachments/sample.hwp' },
								'멀티미디어 자료': { path: '../common/attachments/sample.mp4' },
							},
						},
						{
							lessonNo: '2~3',
							lessonName: ' 1. 여러 가지 용액을 분류해 볼까요?',
							play: '../special/special.html',
							ebook: '../index.html?skin=e-usb&page=6',
							lessonClass: '',
							attachments: {
								'수업 PPT': { path: '../common/attachments/sample.ppt' },
								'멀티미디어 자료': { path: '../common/attachments/sample.mp4' },
							},
						},
						{
							lessonNo: '4',
							lessonName: ' 2. 산성 용액과 염기성 용액의 성질을 관찰해 볼까요?',
							play: '../special/special.html',
							ebook: '../index.html?skin=e-usb&page=12',
							lessonClass: '',
							attachments: { '수업 PPT': { path: '../common/attachments/sample.ppt' } },
						},
						{
							lessonNo: '5',
							lessonName: ' 3. 산성 용액과 염기성 용액을 섞으면 어떻게 될까요?',
							play: '../special/special.html',
							ebook: '../index.html?skin=e-usb&page=18',
							lessonClass: '',
							attachments: {
								'수업 PPT': { path: '../common/attachments/sample.ppt' },
								활동지: { path: '../common/attachments/sample.hwp' },
								'멀티미디어 자료': { path: '../common/attachments/sample.mp4' },
							},
						},
						{
							lessonNo: '6',
							lessonName: ' 4. 우리 주변에서 산성 용액과 염기성 용액을 이용하는 예를 찾아볼까요?',
							play: '../special/special.html',
							ebook: '../index.html?skin=e-usb&page=24',
							lessonClass: '',
							attachments: {
								'수업 PPT': { path: '../common/attachments/sample.ppt' },
								'멀티미디어 자료': { path: '../common/attachments/sample.mp4' },
							},
						},
						{
							lessonNo: '7',
							lessonName: ' 5. 산성화로 인한 환경의 피해 사례를 알아볼까요?',
							play: '../special/special.html',
							ebook: '../index.html?skin=e-usb&page=28',
							lessonClass: '',
						},
						{
							lessonNo: '8~9',
							lessonName: ' 6. 산성화로 인한 환경의 피해 사례를 소개하는 뉴스 영상을 만들고 공유해 보자!',
							play: '../special/special.html',
							ebook: '../index.html?skin=e-usb&page=32',
							lessonClass: '',
							attachments: {
								'수업 PPT': { path: '../common/attachments/sample.ppt' },
								활동지: { path: '../common/attachments/sample.hwp' },
							},
						},
						{
							lessonNo: '과학 이야기',
							lessonName: ' 산호를 지키려는 여러 가지 노력',
							play: '../special/special.html',
							ebook: '../index.html?skin=e-usb&page=38',
							lessonClass: '',
							attachments: {
								'수업 PPT': { path: '../common/attachments/sample.ppt' },
								활동지: { path: '../common/attachments/sample.hwp' },
								'멀티미디어 자료': { path: '../common/attachments/sample.mp4' },
							},
						},
						{ lessonNo: '10', lessonName: ' 스스로 정리해요' },
					],
				},
			],
			attachments: {
				'수업 자료': [
					{ name: '과학', path: '../common/attachments/sample.pdf' },
					{ name: '실험 관찰', path: '../common/attachments/sample.pdf' },
					{ name: '교사용 지도서', path: '../common/attachments/sample.pdf' },
					{ name: '교실지 QR 리스트업 파일', path: '../common/attachments/sample.hwp' },
					{ name: '단원별 차시 계획', path: '../common/attachments/sample.hwp' },
					{ name: '수업 지도안', path: '../common/attachments/sample.zip' },
					{ name: '에듀테크 수업 계획서', path: '../common/attachments/sample.zip' },
					{ name: '과학 이야기 활동지', path: '../common/attachments/sample.hwp' },
					{ name: '진로 적성 활동지_과학과 나의 꿈', path: '../common/attachments/sample.hwp' },
					{ name: '의사전달력_과학 글쓰기', path: '../common/attachments/sample.hwp' },
					{ name: '지역별 견학 체험 자료', path: '../common/attachments/sample.hwp' },
				],
				'평가 자료': [
					{ name: '학생 평가 활동지', path: '../common/attachments/sample.zip' },
					{ name: '학생 평가 활동지', path: '../common/attachments/sample.zip' },
					{ name: '창의적 문제 해결_수행평가', path: '../common/attachments/sample.hwp' },
					{ name: '단원 총괄 평가', path: '../common/attachments/sample.hwp' },
					{ name: '동료 평가 활동지', path: '../common/attachments/sample.hwp' },
				],
				'이미지 자료': [
					{ name: '과학 이미지', path: '../common/attachments/sample.zip' },
					{ name: '실험 관찰 이미지', path: '../common/attachments/sample.zip' },
					{ name: '교과서 밖 이미지', path: '../common/attachments/sample.zip' },
				],
			},
		},
		{
			unitNo: '2',
			unitName: '2. 물체의 운동',
			unitNoIcon: '../../common/img/2/science/num2.png',
			menuTarget: 'lesson-wrap2',
			chapters: [
				{
					chapterName: '',
					lessons: [
						{
							lessonNo: '1',
							lessonName: ' 물체의 운동',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '2',
							lessonName: ' 1. 운동하는 물체의 특징을 알아볼까요?',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '3',
							lessonName: ' 2. 물체의 운동을 어떻게 표현할까요?',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '4',
							lessonName: ' 3. 같은 시간 동안에 물체가 이동한 거리를 비교해 볼까요?',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '5~6',
							lessonName: ' 4. 물체의 속력을 구해 빠르기를 비교해 볼까요?',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{ lessonNo: '7', lessonName: ' 5. 속력과 관련된 안전 수칙과 안전 장치를 조사해 볼까요?' },
						{ lessonNo: '8~9', lessonName: ' 6. 우리 학교 주변 교통안전 지도를 만들어 보자!' },
						{ lessonNo: '과학 이야기', lessonName: ' 차시명 미정' },
						{ lessonNo: '10', lessonName: ' 스스로 정리해요' },
					],
				},
			],
			attachments: {
				'수업 자료': [
					{ name: '과학', path: '../common/attachments/sample.pdf' },
					{ name: '실험 관찰', path: '../common/attachments/sample.pdf' },
					{ name: '교사용 지도서', path: '../common/attachments/sample.pdf' },
					{ name: '교실지 QR 리스트업 파일', path: '../common/attachments/sample.hwp' },
					{ name: '단원별 차시 계획', path: '../common/attachments/sample.hwp' },
					{ name: '수업 지도안', path: '../common/attachments/sample.zip' },
					{ name: '에듀테크 수업 계획서', path: '../common/attachments/sample.zip' },
					{ name: '과학 이야기 활동지', path: '../common/attachments/sample.hwp' },
					{ name: '진로 적성 활동지_과학과 나의 꿈', path: '../common/attachments/sample.hwp' },
					{ name: '의사전달력_과학 글쓰기', path: '../common/attachments/sample.hwp' },
					{ name: '지역별 견학 체험 자료', path: '../common/attachments/sample.hwp' },
				],
				'평가 자료': [
					{ name: '학생 평가 활동지', path: '../common/attachments/sample.zip' },
					{ name: '학생 평가 활동지', path: '../common/attachments/sample.zip' },
					{ name: '창의적 문제 해결_수행평가', path: '../common/attachments/sample.hwp' },
					{ name: '단원 총괄 평가', path: '../common/attachments/sample.hwp' },
					{ name: '동료 평가 활동지', path: '../common/attachments/sample.hwp' },
				],
				'이미지 자료': [
					{ name: '과학 이미지', path: '../common/attachments/sample.zip' },
					{ name: '실험 관찰 이미지', path: '../common/attachments/sample.zip' },
					{ name: '교과서 밖 이미지', path: '../common/attachments/sample.zip' },
				],
			},
		},
		{
			unitNo: '3',
			unitName: '3. 식물의 구조와 기능',
			unitNoIcon: '../../common/img/2/science/num3.png',
			menuTarget: 'lesson-wrap3',
			chapters: [
				{
					chapterName: '',
					lessons: [
						{
							lessonNo: '1',
							lessonName: ' 식물의 구조와 기능',
							lessonPlayIcon: '../../common/img/2/science/icon_science.png',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '2~3',
							lessonName: ' 1. 세포를 관찰해 볼까요?',
							lessonPlayIcon: '../../common/img/2/science/icon_science.png',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '4',
							lessonName: ' 2. 뿌리, 줄기, 잎, 꽃의 구조를 관찰해 볼까요?',
							lessonPlayIcon: '../../common/img/2/science/icon_science.png',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '5',
							lessonName: ' 3. 뿌리의 기능을 알아볼까요?',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '6',
							lessonName: ' 4. 줄기의 기능을 알아볼까요?',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{ lessonNo: '7~8', lessonName: ' 5. 잎의 기능을 알아볼까요?' },
						{ lessonNo: '특화', lessonName: ' 물과 양분의 이동' },
						{ lessonNo: '9', lessonName: ' 6. 꽃의 기능을 알아볼까요?' },
						{ lessonNo: '10', lessonName: ' 7. 여러 가지 식물의 특징을 알아볼까요?' },
						{
							lessonNo: '11~12',
							lessonName: ' 8. 여러 가지 식물의 특징을 설명하는 영상을 만들어 공유해 보자!',
						},
						{ lessonName: ' 숲이 자연에서 하는 일', lessonNo: '과학 이야기' },
						{ lessonName: ' 스스로 정리해요', lessonNo: '13' },
					],
				},
			],
			attachments: {
				'수업 자료': [
					{ name: '과학', path: '../common/attachments/sample.pdf' },
					{ name: '실험 관찰', path: '../common/attachments/sample.pdf' },
					{ name: '교사용 지도서', path: '../common/attachments/sample.pdf' },
					{ name: '교실지 QR 리스트업 파일', path: '../common/attachments/sample.hwp' },
					{ name: '단원별 차시 계획', path: '../common/attachments/sample.hwp' },
					{ name: '수업 지도안', path: '../common/attachments/sample.zip' },
					{ name: '에듀테크 수업 계획서', path: '../common/attachments/sample.zip' },
					{ name: '과학 이야기 활동지', path: '../common/attachments/sample.hwp' },
					{ name: '진로 적성 활동지_과학과 나의 꿈', path: '../common/attachments/sample.hwp' },
					{ name: '의사전달력_과학 글쓰기', path: '../common/attachments/sample.hwp' },
					{ name: '지역별 견학 체험 자료', path: '../common/attachments/sample.hwp' },
				],
				'평가 자료': [
					{ name: '학생 평가 활동지', path: '../common/attachments/sample.zip' },
					{ name: '학생 평가 활동지', path: '../common/attachments/sample.zip' },
					{ name: '창의적 문제 해결_수행평가', path: '../common/attachments/sample.hwp' },
					{ name: '단원 총괄 평가', path: '../common/attachments/sample.hwp' },
					{ name: '동료 평가 활동지', path: '../common/attachments/sample.hwp' },
				],
				'이미지 자료': [
					{ name: '과학 이미지', path: '../common/attachments/sample.zip' },
					{ name: '실험 관찰 이미지', path: '../common/attachments/sample.zip' },
					{ name: '교과서 밖 이미지', path: '../common/attachments/sample.zip' },
				],
			},
		},
		{
			unitNo: '4',
			unitName: '4. 지구의 운동',
			unitNoIcon: '../../common/img/2/science/num4.png',
			menuTarget: 'lesson-wrap4',
			chapters: [
				{
					chapterName: '',
					lessons: [
						{
							lessonNo: '1',
							lessonName: ' 지구의 운동',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '2~3',
							lessonName: ' 1. 하루 동안 태양과 별의 위치는 어떻게 달라질까요?',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '4',
							lessonName: ' 2. 하루 동안 지구는 어떻게 운동할까요?',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '5',
							lessonName: ' 3. 낮과 밤이 생기는 까닭은 무엇일까요?',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{
							lessonNo: '6',
							lessonName: ' 4. 일 년 동안 지구는 어떻게 운동할까요?',
							play: '',
							ebook: '../index.html?skin=e-ubs&page={페이지}',
							lessonClass: '',
						},
						{ lessonNo: '7~8', lessonName: ' 5. 계절에 따라 달라지는 별자리를 관찰해 볼까요?' },
						{ lessonNo: '9', lessonName: ' 6. 지구의 운동을 관찰해 볼까요?' },
						{ lessonNo: '10~11', lessonName: ' 7. 지구의 운동 모형을 만들고 소개해 보자!' },
						{ lessonNo: '과학 이야기', lessonName: ' 기후변화가 지구 시간도 바꾼다.' },
						{ lessonNo: '12', lessonName: ' 스스로 정리해요' },
					],
				},
			],
			attachments: {
				'수업 자료': [
					{ name: '과학', path: '../common/attachments/sample.pdf' },
					{ name: '실험 관찰', path: '../common/attachments/sample.pdf' },
					{ name: '교사용 지도서', path: '../common/attachments/sample.pdf' },
					{ name: '교실지 QR 리스트업 파일', path: '../common/attachments/sample.hwp' },
					{ name: '단원별 차시 계획', path: '../common/attachments/sample.hwp' },
					{ name: '수업 지도안', path: '../common/attachments/sample.zip' },
					{ name: '에듀테크 수업 계획서', path: '../common/attachments/sample.zip' },
					{ name: '과학 이야기 활동지', path: '../common/attachments/sample.hwp' },
					{ name: '진로 적성 활동지_과학과 나의 꿈', path: '../common/attachments/sample.hwp' },
					{ name: '의사전달력_과학 글쓰기', path: '../common/attachments/sample.hwp' },
					{ name: '지역별 견학 체험 자료', path: '../common/attachments/sample.hwp' },
				],
				'평가 자료': [
					{ name: '학생 평가 활동지', path: '../common/attachments/sample.zip' },
					{ name: '학생 평가 활동지', path: '../common/attachments/sample.zip' },
					{ name: '창의적 문제 해결_수행평가', path: '../common/attachments/sample.hwp' },
					{ name: '단원 총괄 평가', path: '../common/attachments/sample.hwp' },
					{ name: '동료 평가 활동지', path: '../common/attachments/sample.hwp' },
				],
				'이미지 자료': [
					{ name: '과학 이미지', path: '../common/attachments/sample.zip' },
					{ name: '실험 관찰 이미지', path: '../common/attachments/sample.zip' },
					{ name: '교과서 밖 이미지', path: '../common/attachments/sample.zip' },
				],
			},
		},
	],
};
